services:
  - type: web
    name: college-attendance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn attendance.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: your_postgresql_database_url
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
